### ISSUE TITLE
Sticky column cells not aligned with other columns

### ISSUE THREAD

**Issue by paulshen** [githubocto/flat-ui#20]
I encountered a few issues that I wanted to share in case useful. I'm currently only playing with the library so not necessary to fix!

In the sandbox, https://codesandbox.io/s/dazzling-cray-bjmjs, hovering the sticky column seems to highlight a different row in the rest of the table.

![image](https://user-images.githubusercontent.com/2266187/150475658-10ac3c93-1f67-4aeb-b41e-18ee81595ed4.png)

Switching between pinning the first and second column seems to shuffle the contents of the first two column. This might be related to previous item.

I tried using the component inside another tailwind project nested inside a div that also has a `group` class name which causes hover elements to show up too aggressively. Could call this a usage issue :)

![image](https://user-images.githubusercontent.com/2266187/150476065-a9a4a00a-d200-41e1-ac32-ddc376e11423.png)

**Comment by Wattenberger** [comment]
All super helpful feedback, thanks Paul!
