### ISSUE TITLE
Show number of columns in the summary row

### ISSUE THREAD

**Issue by RandomFractals** [githubocto/flat-ui#26]
Latest version of this data grid displays the number of data rows in a grid footer.

I think it would be valuable to see the number of columns there too, similar to how most data frame libraries display them now.

Example of `df.head` table display:

![kaggle-df-head](https://user-images.githubusercontent.com/656833/159480171-38dcc405-9433-4723-9f0b-c72e7ed3f57d.png)

Also, I was able to integrate it into VSCode Data Table renders extension and plan to ship that update soon.

I hope this addition will improve datasets preview in VSCode Jupyter notebooks. Example:

![world-rivers-flat-data-grid-renderer-view](https://user-images.githubusercontent.com/656833/159480781-7f6baec7-eb5a-4529-8b5e-180b6b8562ab.png)

Extension: https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-table

**Comment by Wattenberger** [comment]
makes sense! and looks great in the vscode ui!
